#docker-compose for development
version: '3'

services:
  gwts-api:
    build: .
    container_name: gwts-api-server-dev
    image: gwts-api-server
    ports:
      - '9002:9002'
    environment:
      PORT: 9002
      DATABASE_HOST: postgres
      DATABASE_NAME: gwts
      DATABASE_USER: docker
      DATABASE_PORT: 5432
      DATABASE_ACCESS_KEY: docker
      LOG_LEVEL: info
      JWT_SECRET: something
      JWT_REFRESH_SECRET: else

  postgres:
    image: postgres:12.5
    restart: unless-stopped
    volumes:
      - ./docker-data/postgresql:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_DB: gwts
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432

  redis:
    image: 'redis:6.2.6-alpine'
    hostname: redis
    # --save bump data into disk but appendonly is better in this case
    command: redis-server --appendonly yes --loglevel warning
    volumes:
        - ./docker-data/redis:/data
    ports:
      - '6379:6379'

  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - '8081:8081'
